import 'package:cloud_firestore/cloud_firestore.dart';

class BookingModel {
  final String id;            // Unique ID for the booking (auto-generated by Firebase)
  final String userId;        // ID of the user who made the booking
  final String courtName;     // e.g., "Court A (Badminton)"
  final String sportType;     // "Badminton" or "Futsal"
  final DateTime bookingDate; // The date of the game
  final String timeSlot;      // e.g., "18:00 - 19:00"
  final double totalPrice;    // The amount to be paid at the counter
  final String status;        // "Confirmed", "Cancelled", "Completed"
  final String paymentStatus; // "Unpaid (Pay at Counter)" or "Paid"
  final DateTime createdAt;   // Timestamp when the booking was made

  BookingModel({
    required this.id,
    required this.userId,
    required this.courtName,
    required this.sportType,
    required this.bookingDate,
    required this.timeSlot,
    required this.totalPrice,
    required this.status,
    required this.paymentStatus,
    required this.createdAt,
  });

  // 1. Convert a BookingModel object into a Map to save to Firebase (Create)
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'courtName': courtName,
      'sportType': sportType,
      'bookingDate': Timestamp.fromDate(bookingDate), // Firebase uses Timestamp
      'timeSlot': timeSlot,
      'totalPrice': totalPrice,
      'status': status,
      'paymentStatus': paymentStatus,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }

  // 2. Create a BookingModel object from a Firebase Map (Read)
  // This is used when fetching data from the database to display in "My Bookings"
  factory BookingModel.fromMap(Map<String, dynamic> map, String documentId) {
    return BookingModel(
      id: documentId,
      userId: map['userId'] ?? '',
      courtName: map['courtName'] ?? '',
      sportType: map['sportType'] ?? 'Badminton',
      // Handle conversion from Firebase Timestamp to Dart DateTime
      bookingDate: (map['bookingDate'] as Timestamp).toDate(),
      timeSlot: map['timeSlot'] ?? '',
      totalPrice: (map['totalPrice'] ?? 0).toDouble(),
      status: map['status'] ?? 'Confirmed',
      paymentStatus: map['paymentStatus'] ?? 'Unpaid',
      createdAt: (map['createdAt'] as Timestamp).toDate(),
    );
  }
}